# Generated by Django 5.2 on 2025-05-06 13:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('status', models.CharField(choices=[('unread', 'خوانده نشده'), ('read', 'خوانده شده'), ('replied', 'پاسخ داده شده')], default='unread', max_length=10, verbose_name='وضعیت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان خدمت')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='آدرس URL')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیح کوتاه')),
                ('icon', models.CharField(help_text='نام آیکون از فونت Awesome', max_length=50, verbose_name='آیکون')),
                ('image', models.ImageField(upload_to='services/', verbose_name='تصویر شاخص')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('position', models.CharField(max_length=100, verbose_name='سمت')),
                ('bio', models.TextField(verbose_name='بیوگرافی')),
                ('image', models.ImageField(upload_to='team/', verbose_name='تصویر')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن')),
                ('linkedin', models.URLField(blank=True, verbose_name='لینکدین')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'اعضای تیم',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='آدرس URL')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('excerpt', models.CharField(max_length=300, verbose_name='چکیده')),
                ('cover_image', models.ImageField(upload_to='blog/', verbose_name='تصویر شاخص')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-publish_date'],
            },
        ),
    ]
